name: Deploy HVAC Frontend to Amazon S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - production
          - development

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ github.event.inputs.environment == 'production' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.environment == 'production' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/hvac/package-lock.json

      - name: Install dependencies
        working-directory: frontend/hvac
        run: npm ci

      - name: Build
        working-directory: frontend/hvac
        run: npm run build -- --configuration "${{ github.event.inputs.environment }}"
   
      - name: Copy files to S3
        working-directory: frontend/hvac
        run: |
          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            aws s3 sync dist/hvac/browser s3://${{ vars.PROD_S3_BUCKET_FRONTEND }} --delete
          else
            aws s3 sync dist/hvac/browser s3://${{ vars.DEV_S3_BUCKET_FRONTEND }} --delete
          fi